version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/bash -c "while sleep 1000; do :; done"
    ports:
      - 4242:4242
